---
title: "Final"
author: "Jackson Dial"
date: "4/12/2022"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(table1)
library(tidyverse)
library(olsrr) #for stepwise regression
library(pander) #for cleaning up the outputs
library(broom)
```

```{r}
dat1 <- read.csv("Data/dig.csv")
```

# Cleaning

```{r}
#first check variables of interest for NA values
sum(is.na(dat1$TRTMT))
sum(is.na(dat1$WHF))
sum(is.na(dat1$AGE))
sum(is.na(dat1$KLEVEL)) #This is an issue, there are 801 observations here that are NA
table(dat1$KLEVEL)
summary(dat1$KLEVEL) #also has a very large outlier. Would appear that it should be 4.3, but I will likely just remove it because it is just one observation

table(dat1$RACE)
sum(is.na(dat1$race))

summary(dat1$SEX)
summary(dat1$CREAT)
summary(dat1$SYSBP) # 3 NA values
summary(dat1$DIABP) # 5 NA values
summary(dat1$FUNCTCLS) #6 NA
summary(dat1$CHFETIOL) #18 NA
summary(dat1$PREVMI) #1 NA
summary(dat1$DIABETES)
summary(dat1$HYPERTEN) #1 NA

table(dat1$DIURETK)
summary(dat1$DIURETK)
table(dat1$KSUPP)
summary(dat1$KSUPP) #662
summary(dat1$AGE)
summary(dat1$BMI) #has 1 NA
summary(dat1$NSYM)

```

# Table 1 for Aim 1

```{r}
table_dat <- dat1 %>% 
  transmute(Sex =
              case_when(SEX == 1 ~ "Male",
                        TRUE ~ "Female"),
            Race = 
              case_when(RACE == 1 ~ "White",
                        TRUE ~ "Non-White"),
            Treatment =
              case_when(TRTMT == 0 ~ "Placebo",
                        TRUE ~ "Digoxin",),
            `Serum Creatinine` = CREAT,
            `Serum Potassium` = KLEVEL,
            SystolicBP = SYSBP,
            DiastolicBP = DIABP,
            `NYHA Class` = 
              case_when(FUNCTCLS == 1 ~ "Class I",
                        FUNCTCLS == 2 ~ "Class II",
                        FUNCTCLS == 3 ~ "Class III",
                        FUNCTCLS == 4 ~ "Class IV"),
            `CHF Etiology` =
              case_when(CHFETIOL == 1 ~ "Ischemic",
                        CHFETIOL == 2 ~ "Hypertensive",
                        CHFETIOL == 3 ~ "Valvular",
                        CHFETIOL == 4 ~ "Idiopathic",
                        CHFETIOL == 5 ~ "Alcohol Related",
                        CHFETIOL == 6 ~ "Other"),
            `Previous Myocardial Infarction` =
              case_when(PREVMI == 0 ~ "No",
                        TRUE ~ "Yes"),
            `History of Diabetes` =
              case_when(DIABETES == 0 ~ "No",
                        TRUE ~ "Yes"),
            `History of Hypertension` =
              case_when(HYPERTEN == 0 ~ "No",
                        TRUE ~ "Yes"),
            `Potassium-Sparing Diuretics` =
              case_when(DIURETK == 0 ~ "No",
                        TRUE ~ "Yes"),
            `Potassium Supplement` =
              case_when(KSUPP == 0 ~ "No",
                        TRUE ~ "Yes"),
            `Age of Patient` = AGE,
            `BMI of Patient` = BMI,
            `Number of CHF Symptoms` = NSYM,
            `Worsened Heart Failure` =
              case_when(WHF == 0 ~ "No",
                        TRUE ~ "Yes")
            )

table1( ~ . | `Treatment`, data = table_dat)

```

# Aim 1

```{r}
aim1_dat <- dat1 %>% 
  select(KLEVEL, SEX, RACE, TRTMT, CREAT, SYSBP, DIABP, FUNCTCLS, CHFETIOL, PREVMI, DIABETES, HYPERTEN, DIURETK, KSUPP, AGE, BMI, NSYM) %>% 
  filter(KLEVEL < 6.4, #remove outlier of 434 (-1)
         is.na(KLEVEL) == 0, #remove all NA values, there are 801 (-801)
         is.na(SYSBP) == 0, #remove all NA values (-3)
         is.na(DIABP) == 0, #remove all NA values (-5)
         is.na(BMI) == 0, #remove all NA values (-1)
         is.na(KSUPP) == 0, #
         is.na(FUNCTCLS) == 0, #
         is.na(CHFETIOL) == 0, #
         is.na(PREVMI) == 0, #
         is.na(HYPERTEN) == 0 #

  )

sum(is.na(aim1_dat))
```

### P

```{r}
fit1 <- lm(KLEVEL ~ ., data = aim1_dat)
summary(fit1)

ols_step_both_p(fit1, pent = .05, prem = .05) %>% pander()
ols_step_forward_p(fit1, penter = .05) %>% pander()
ols_step_backward_p(fit1, prem = .05) %>% pander()

p_fit <- lm(KLEVEL ~ DIABETES + CREAT, data = aim1_dat)
summary(p_fit)

par(mfrow = c(1,3))
plot(p_fit, which = 1:3)
```

### AIC

```{r}
ols_step_both_aic(fit1) %>% pander()
ols_step_forward_aic(fit1) %>% pander()
ols_step_backward_aic(fit1) %>% pander()
```


# Aim 2

```{r}
aim2_dat <- dat1 %>% 
  filter(KLEVEL < 6.4,
         is.na(KLEVEL) == 0) %>% 
  select(WHF, KLEVEL)
  
sum(is.na(aim2_dat))
```

```{r}
fit2 <- glm(formula = (WHF == 1) ~ KLEVEL, data = aim2_dat, family = "binomial")
summary(fit2) %>% pander()
```

```{r}
exp(-.02429)
```

### Check logistic reg assumptions

#### Assumption 4

```{r}
logodds <- fit2$linear.predictors
plot(logodds ~ KLEVEL, data = aim2_dat)
```


#### Assumption 5

```{r}
table(aim2_dat$WHF) %>% pander()
table(table_dat$`Worsened Heart Failure`) %>% pander()
```

# Aim 3

```{r}
aim3_dat <- dat1 %>% 
  select(WHF, KLEVEL, TRTMT) %>% 
  filter(is.na(KLEVEL) == 0,
         KLEVEL < 6.4)
sum(is.na(aim3_dat))
```

```{r}
fit3 <- glm(formula = (WHF == 1) ~ KLEVEL + as.factor(TRTMT), data = aim3_dat, family = "binomial")

summary(fit3)
```

```{r}
ggplot(aim3_dat, aes(x = KLEVEL, y = WHF, col = as.factor(TRTMT)))+
  geom_point(alpha = .2, size = 4)+
  geom_jitter(width = NULL)

```

```{r}
exp(-.01891)
exp(-.37355)
```


```{r}
vif(fit3)

logodds <- fit3$linear.predictors
plot(logodds ~ KLEVEL + as.factor(TRTMT), data = aim3_dat)

```

